{{- include "ph.validate" . }}
{{- if and .Values.token.value (not .Values.token.existingSecret) (not .Values.tenants.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ph.tokenSecret" . }}
  labels: {{- include "ph.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.token.existingSecretKey }}: {{ .Values.token.value | quote }}
{{- end }}
{{- if and .Values.postgres.url (not .Values.postgres.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ph.fullname" . }}-postgres
  labels: {{- include "ph.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.postgres.url | quote }}
{{- end }}
